### ISSUE TITLE
Stream not played in background when navigating menus

### ISSUE THREAD

**Issue by fipm** [chrisbevan/skin.pellucid#10] opened 2016-07-10 16:04 UTC
I am not sure if it is intended behaviour or not, but I noticed that unlike with maximinimalism - which I love dearly! - when navigating the menus with a stream playing, the stream does not replace the background.

**Comment by chrisbevan** [comment] 2016-07-18 15:37
Hi fipm,

It is intended behaviour i'm afraid. Allowing fullscreen video behind the menus just doesn't suit the design I was going for!

**Comment by chrisbevan** [comment] 2016-07-25 20:03
BTW: I'll be returning to Maximinimalism shortly, preparing version 2.0 for a Krypton release.

**Comment by fipm** [comment] 2016-08-10 20:05
Great news! Can't wait for it!

**Comment by chrisbevan** [comment] 2016-12-09 10:26
Fixed in Pellucid Krypton branch

**Closed by chrisbevan** 2016-12-09 10:26 UTC
